name: recipe-finder

services:
  client:
    build: .
    command: npm run start
    ports: 
     - 3000:3000
    volumes:
     - ./:/code
     - /code/node_modules
    environment:
    - REACT_APP_API_URL=http://127.0.0.1:5000
    - REACT_APP_TOKEN_REFRESH_RATE=300
    - REACT_APP_ENV=development